version: '3.9'
services:
  mongo:
    image: mongo:4.4
    container_name: nightscout-mongo
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    networks:
      - nightscout_network
  nightscout:
    image: nightscout/cgm-remote-monitor:latest
    container_name: nightscout
    restart: always
    depends_on:
      - mongo
    ports:
      - "7380:1337"
    environment:
      ### Variables for the container
      NODE_ENV: production
      ALARM_HIGH: ${ALARM_HIGH}
      ALARM_LOW: ${ALARM_LOW}
      ALARM_TIMEAGO_URGENT: ${ALARM_TIMEAGO_URGENT}
      ALARM_TIMEAGO_URGENT_MINS: ${ALARM_TIMEAGO_URGENT_MINS}
      ALARM_TIMEAGO_WARN: ${ALARM_TIMEAGO_WARN}
      ALARM_TIMEAGO_WARN_MINS: ${ALARM_TIMEAGO_WARN_MINS}
      ALARM_TYPES: ${ALARM_TYPES}
      ALARM_URGENT_HIGH: ${ALARM_URGENT_HIGH}
      ALARM_URGENT_LOW: ${ALARM_URGENT_LOW}
      API_SECRET: ${API_SECRET}
      AUTH_DEFAULT_ROLES: ${AUTH_DEFAULT_ROLES}
      BG_HIGH: ${BG_HIGH}
      BG_LOW: ${BG_LOW}
      BG_TARGET_BOTTOM: ${BG_TARGET_BOTTOM}
      BG_TARGET_TOP: ${BG_TARGET_TOP}
      BOLUS_RENDER_OVER: ${BOLUS_RENDER_OVER}
      DISPLAY_UNITS: ${DISPLAY_UNITS}
      BRIDGE_USERNAME: ${BRIDGE_USERNAME}
      BRIDGE_PASSWORD: ${BRIDGE_PASSWORD}
      BRIDGE_SERVER: ${BRIDGE_SERVER}
      ENABLE: ${ENABLE}
      MONGODB_URI: mongodb://mongo:27017/nightscout
      NIGHT_MODE: ${NIGHT_MODE}
      SHOW_PLUGINS: ${SHOW_PLUGINS}
      SHOW_RAWBG: ${SHOW_RAWBG}
      THEME: ${THEME}
      TIME_FORMAT: ${TIME_FORMAT}
      BASE_URL: ${BASE_URL}
      INSECURE_USE_HTTP: ${INSECURE_USE_HTTP}
    networks:
      - nightscout_network
  tconnectsync:
    image: ghcr.io/jwoglom/tconnectsync/tconnectsync:2.3.4
    container_name: tconnectsync
    restart: unless-stopped
    environment:
      TCONNECT_EMAIL: ${TCONNECT_EMAIL}
      TCONNECT_PASSWORD: ${TCONNECT_PASSWORD}
      TCONNECT_REGION: EU
      NS_URL: ${BASE_URL}
      NS_SECRET: ${API_SECRET}
      TIMEZONE_NAME: Europe/London
    command: --auto-update
    networks:
      - nightscout_network

volumes:
  mongo-data:

networks:
   nightscout_network:
    